### ISSUE TITLE
Few workers memory on grafana is not accurate

### ISSUE THREAD

**Issue by psuriset** [redhat-performance/cfme-performance#43]
Few workers memory on grafana is not accurate

Like Refreshworks, MetricsCollector worker..etc

**Comment by psuriset** [comment]
![grafana_cfme_mem](https://user-images.githubusercontent.com/13145336/33643275-11b2050a-da64-11e7-8c53-f707f7faa528.png)

**Comment by arcolife** [comment]
@psuriset could you add more details about the problem you see in this screenshot? if you could add a provider specific dashboard screenshot/anomaly that'd be great. thanks! 
btw you're trying to point out the 10GiB Refresh worker usage in one of our experiments? IIRC it usually adds up all memory from all workers.

**Comment by psuriset** [comment]
@arcolife  @hroyrh  I see 0MB for most of the workers on grafana dashboard. But i see collector worker using more than 900MB

[----] I, [2017-12-05T22:48:44.886024 #28709:727130]  INFO -- : MIQ(MiqAeEngine.deliver) Delivering {:event_type=>"evm_worker_memory_exceeded", :event_details=>"Worker [ManageIQ::Providers::Openshift::ContainerManager::MetricsCollectorWorker] with ID: [4015], PID: [1700], GUID: [5e1892c5-44fb-4d82-b0e9-4ecaf9f73433] process memory usage [911074000] exceeded limit [838860800], requesting worker to exit", :type=>"ManageIQ::Providers::Openshift::ContainerManager::MetricsCollectorWorker", "MiqEvent::miq_event"=>16373, :miq_event_id=>16373, "EventStream::event_stream"=>16373, :event_stream_id=>16373} for object [MiqServer.1] with state [] to Automate

**Comment by arcolife** [comment]
@psuriset you're looking at generic performance dashboard which puts panels from all providers in one place.

Since the context here is OCP, you'd wanna use `manageiq-scale-openshift-enterprise-system-performance-with-statsd`. I see no problem with memory there. 

In your screenshot above, you're looking at Openstack::CloudManager:RefreshWorker, which your log fragment points to ManageIQ::Providers::Openshift::ContainerManager::MetricsCollectorWorker

Do you have both OCP and OSP connected ? if so, generic dashboard makes sense. Even then, I opened up generic one and it shows me OCP related workers with sensible memory figures.

![screenshot from 2017-12-06 13-37-08](https://user-images.githubusercontent.com/920859/33651124-bd81f82e-da8a-11e7-8c93-8e82a1d61dd7.png)
![screenshot from 2017-12-06 13-37-00](https://user-images.githubusercontent.com/920859/33651126-bdb48b4a-da8a-11e7-849f-5d026cf6c592.png)
![screenshot from 2017-12-06 13-36-51](https://user-images.githubusercontent.com/920859/33651127-bde561de-da8a-11e7-80a9-6d46d91e7454.png)
![screenshot from 2017-12-06 13-36-43](https://user-images.githubusercontent.com/920859/33651128-be1374ac-da8a-11e7-863c-40ff60db919f.png)

**Comment by psuriset** [comment]
Thanks @arcolife
